/**
 * Curated pool of 300 specific, photogenic locations for prompt generation.
 * Organized by category for maintainability. Selected by true randomness
 * (Math.random) rather than AI to guarantee diversity across batches.
 */

const LOCATIONS: string[] = [
	// ── Coastal & Beach (30) ──
	'A weathered fishing dock in Porto, Portugal with peeling blue paint and coiled ropes',
	'A secluded black sand beach in Vík, Iceland with basalt sea stacks in the background',
	'A turquoise cove in Sardinia, Italy with limestone cliffs and anchored sailboats',
	'A palm-lined boardwalk in Santa Monica, California during late afternoon light',
	'A coral-pink beach in Harbour Island, Bahamas with crystal-clear shallow water',
	'A dramatic sea cliff in Étretat, France with natural stone arches',
	'A rustic oyster shack on the coast of Cancale, Brittany with stacked shells',
	'A windswept dune beach in Jericoacoara, Brazil with tilted palm trees',
	'A volcanic shoreline in Lanzarote, Canary Islands with black lava rock pools',
	'A sleepy fishing village beach in Cinque Terre, Italy with colorful boats pulled ashore',
	'A wild surf beach in Nazaré, Portugal with whitewashed cliffside buildings above',
	'A mangrove-fringed shore in Zanzibar, Tanzania at low tide with dhow boats',
	'A misty morning beach in Big Sur, California with fog rolling over sea stacks',
	'A white-sand cove in Navagio Beach, Zakynthos, Greece with towering cliff walls',
	'A rocky tidal pool area in Cape Town, South Africa with Table Mountain in the distance',
	'A quiet pier at Lake Bled, Slovenia with the island church in the background',
	'A remote beach on Socotra Island, Yemen with dragon blood trees on the hillside',
	'A bioluminescent bay shore in Vieques, Puerto Rico at twilight',
	'A wave-battered coastline in Faroe Islands with grass-roofed houses on the cliff',
	'A tropical lagoon in Bora Bora, French Polynesia with overwater bungalows',
	'A shell-covered beach in Sanibel Island, Florida during golden hour',
	'A limestone karst bay in Ha Long Bay, Vietnam with floating fishing villages',
	'A surfboard-lined beach in Byron Bay, Australia with eucalyptus-covered headlands',
	'A frozen lakeside shore in Lake Baikal, Siberia with turquoise ice formations',
	'A pristine coral beach in Maldives with a sandbar extending into open ocean',
	'A dramatic fjord beach in Lofoten, Norway with snow-capped peaks and red cabins',
	'A sun-bleached wooden pier in Key West, Florida at sunset',
	'A pebble beach in Nice, France with the Promenade des Anglais curving behind',
	'A hidden sea cave beach in Lagos, Algarve, Portugal with golden rock formations',
	'A windswept headland in Dingle Peninsula, Ireland with ancient stone walls',

	// ── Urban & City (35) ──
	'A rain-slicked street in Shibuya, Tokyo with neon reflections on wet pavement',
	'A cobblestone alley in Prague, Czech Republic with wrought-iron lanterns at dusk',
	'A graffiti-covered underpass in Shoreditch, London with street art murals',
	'A wide tree-lined boulevard in Buenos Aires, Argentina with Art Deco facades',
	'A narrow canal-side street in Utrecht, Netherlands with bicycle-lined railings',
	'A rooftop pool overlooking the skyline of Singapore at blue hour',
	'A vintage tram stop in Lisbon, Portugal on a steep hill with tiled building facades',
	'A bustling intersection in Myeongdong, Seoul with hanging shop signs',
	'A quiet courtyard in Marrakech, Morocco with a tiled fountain and orange trees',
	'A fog-wrapped street in San Francisco with Victorian row houses and steep hills',
	'A flower-filled balcony on a canal in Annecy, France with pastel buildings',
	'A modernist plaza in Barcelona, Spain with geometric shadows from Gaudí architecture',
	'A lantern-lit old quarter street in Hoi An, Vietnam at twilight',
	'A snow-dusted street in Tallinn, Estonia with medieval merchant houses',
	'A palm-shaded plaza in Havana, Cuba with vintage American cars parked outside',
	'A winding medieval street in Siena, Italy with terracotta-toned walls',
	'A glass-and-steel financial district walkway in Dubai at golden hour',
	'A cherry blossom-lined canal path in Kyoto, Japan in spring',
	'A converted industrial loft district in Brooklyn, New York with fire escapes',
	'A grand Art Nouveau arcade in Brussels, Belgium with ornate iron and glass',
	'A sunlit piazza in Florence, Italy with Renaissance architecture and stone benches',
	'A vibrant street in Valparaíso, Chile painted with murals on every surface',
	'A misty morning on a bridge over the Vltava River in Prague',
	'A bustling night street in Bangkok, Thailand with food vendor steam and lights',
	'A quiet residential lane in Notting Hill, London with pastel-colored townhouses',
	'A waterfront promenade in Thessaloniki, Greece with the White Tower in view',
	'A colonial-era arcade in George Town, Penang with shophouses and street art',
	'A wide pedestrian boulevard in Vienna, Austria with Baroque building facades',
	'A steep funicular railway platform in Valparaíso, Chile overlooking the harbor',
	'A stone-paved square in Dubrovnik, Croatia with terracotta roofs and bell towers',
	'A futuristic transit hub in Liège-Guillemins, Belgium with sweeping white arches',
	'A candlelit alley in a Venetian backstreet at dusk with laundry lines overhead',
	'A hip coffee district in Melbourne, Australia with exposed-brick lane art',
	'A wide avenue in Champs-Élysées, Paris at blue hour with streaming traffic lights',
	'A riverside boardwalk in Porto Alegre, Brazil with modern art installations',

	// ── Mountain & Alpine (25) ──
	'A wooden suspension bridge over a gorge in the Swiss Alps with fog below',
	'A high-altitude meadow in Dolomites, Italy with wildflowers and jagged peaks',
	'A stone shepherd hut in the Scottish Highlands with heather-covered hills',
	'A glacier overlook platform in Jasper, Canada with turquoise meltwater below',
	'A misty tea plantation terrace in Munnar, Kerala, India',
	'A winding mountain road in Trollstigen, Norway with switchbacks and waterfalls',
	'A Tibetan prayer flag ridge at Annapurna Base Camp, Nepal',
	'A cable car station above Chamonix, France with Mont Blanc in the background',
	'A volcanic crater rim in Mount Bromo, Java, Indonesia at sunrise',
	'A snow-dusted wooden chalet balcony in Zermatt, Switzerland facing the Matterhorn',
	'A rocky alpine lake shore in Torres del Paine, Patagonia with granite towers',
	'A dense cloud forest path in Monteverde, Costa Rica with hanging moss',
	'A summit ridge in the Tatras, Slovakia with panoramic valley views',
	'A traditional mountain village in Hallstatt, Austria reflected in the lake',
	'A bamboo forest trail on a misty mountain in Sapa, Vietnam',
	'A high desert plateau in Ladakh, India with Buddhist monastery walls',
	'A glacial moraine in the Canadian Rockies with powder-blue water',
	'A terraced vineyard hillside in the Douro Valley, Portugal in autumn',
	'A stone lookout point on Table Mountain, Cape Town with city below',
	'A hot spring pool in the mountains of Hakone, Japan with steam rising',
	'A wildflower-blanketed hillside in the Caucasus Mountains, Georgia',
	'A cliffside monastery in Meteora, Greece perched on sandstone pillars',
	'A frozen waterfall in Plitvice Lakes, Croatia in winter',
	'A mountain pass road in Karakoram Highway, Pakistan with snow peaks',
	'A sunrise viewpoint at Machu Picchu, Peru with Huayna Picchu behind',

	// ── Desert & Arid (20) ──
	'A cracked salt flat in Death Valley, California with polygon patterns at dawn',
	'A sandstone slot canyon in Page, Arizona with light beams piercing through',
	'A traditional mud-brick village in Aït Benhaddou, Morocco at sunset',
	'A vast red sand dune field in Sossusvlei, Namibia with dead acacia trees',
	'A desert oasis with date palms in Siwa, Egypt with a natural spring pool',
	'A wind-carved rock formation in White Desert, Egypt under a starry sky',
	'A nomad camp in the Sahara Desert, Morocco with camel silhouettes',
	'A turquoise hot spring in the Danakil Depression, Ethiopia with mineral deposits',
	'A cactus-studded valley in the Tatacoa Desert, Colombia at golden hour',
	'A red rock canyon overlook in Sedona, Arizona with juniper trees',
	'A painted desert hillside in the Zhangye Danxia, China with rainbow layers',
	'A dry lakebed at Racetrack Playa, Death Valley with mysterious sailing stones',
	'A moonlit desert highway stretching to infinity in the Mojave, California',
	'A crumbling adobe pueblo in the Atacama Desert, Chile with clear night sky',
	'A petrified forest clearing in the Arizona Painted Desert with scattered logs',
	'A canyon rim at sunset in Wadi Rum, Jordan with Bedouin tent below',
	'A volcanic caldera floor in Lanzarote with twisted lava formations',
	'An ancient caravan route through the Thar Desert, Rajasthan, India',
	'A geothermal mud pool area in Hverir, Iceland with sulfur-stained earth',
	'A vast expanse of cracked clay at Etosha Pan, Namibia with heat haze',

	// ── Forest & Jungle (20) ──
	'A moss-draped old-growth forest in Olympic National Park, Washington',
	'A bamboo grove tunnel in Arashiyama, Kyoto, Japan with dappled light',
	'A misty redwood grove in Muir Woods, California with fern-covered floor',
	'A bioluminescent fungi trail in a New Zealand beech forest at night',
	'A suspended canopy walkway in Taman Negara, Malaysia above the rainforest',
	'A sun-dappled birch forest in Finland with golden autumn leaves',
	'A flooded cypress swamp in Louisiana with Spanish moss and still water',
	'A tropical waterfall pool in El Yunque, Puerto Rico surrounded by giant ferns',
	'A cedar forest shrine path in Kumano Kodo, Japan with stone lanterns',
	'A buttress-root trail in Daintree Rainforest, Australia with filtered light',
	'A eucalyptus forest clearing in the Blue Mountains, Australia with blue haze',
	'A twisted oak forest in Wistmans Wood, Dartmoor, England with lichen-covered boulders',
	'A firefly-lit forest clearing in the Great Smoky Mountains at dusk',
	'A jungle river crossing in Borneo with rope bridge and canopy above',
	'A frost-covered pine forest in Lapland, Finland at dawn with pink sky',
	'A tropical cloud forest with orchids and bromeliads in Mindo, Ecuador',
	'A mushroom-dotted forest floor in the Black Forest, Germany after rain',
	'A giant sequoia grove in Kings Canyon, California with human-dwarfing trunks',
	'A mangrove boardwalk in Sundarbans, Bangladesh at golden hour',
	'A ancient beech forest cathedral in Hallerbos, Belgium during bluebell season',

	// ── Waterfront: Rivers, Lakes, Waterfalls (20) ──
	'A wooden canoe on a mirror-still lake in Banff, Canada with mountain reflections',
	'A cascading waterfall with rainbow mist at Iguazú Falls, Argentina',
	'A houseboat on the Kerala backwaters, India with coconut palms lining the canal',
	'A rustic boathouse on Lake Como, Italy with cypress trees and terraced gardens',
	'A bamboo raft on the Li River, Guilin, China with karst limestone peaks',
	'A swimming hole beneath a waterfall in Havasu Falls, Arizona with turquoise water',
	'A wooden dock on Lake Atitlán, Guatemala with volcanic peaks across the water',
	'A riverside temple complex in Varanasi, India with ghats descending to the Ganges',
	'A serene pond in the gardens of Versailles, France with sculpted hedges',
	'A wild swimming spot in the River Dart, Devon, England with mossy boulders',
	'A hot river in Reykjadalur, Iceland with steam rising between green hillsides',
	'A paddle boarder on Moraine Lake, Canada with the Valley of the Ten Peaks',
	'A riverside cherry blossom walk along the Meguro River, Tokyo in spring',
	'A reflective alpine tarn in Milford Sound, New Zealand with sheer cliff walls',
	'A rowboat on Phewa Lake, Pokhara, Nepal with the Annapurna range reflected',
	'A stepped waterfall with swimmers at Kuang Si Falls, Luang Prabang, Laos',
	'A glassy fjord surface in Geirangerfjord, Norway with abandoned farms on cliffs',
	'A lazy river bend in the Ozarks, Missouri with autumn-colored bluffs',
	'A cenote swimming hole in Yucatán, Mexico with vines hanging from the opening',
	'A canal lock in Stratford-upon-Avon, England with a narrowboat and wildflowers',

	// ── Indoor & Architectural (25) ──
	'A grand reading room in the New York Public Library with arched windows and green lamps',
	'A spiral staircase in a Baroque palace in Vienna, Austria with gilded railings',
	'A sunlit atrium in the Louvre, Paris with the glass pyramid overhead',
	'A vintage bookshop interior in Porto, Portugal with ornate wooden shelves to the ceiling',
	'A minimalist Japanese ryokan room with tatami mats and a garden view',
	'A cathedral interior in Sagrada Família, Barcelona with tree-like columns and colored light',
	'A cozy fireplace nook in a centuries-old English pub with exposed beam ceiling',
	'A grand marble hammam interior in Istanbul, Turkey with domed skylights',
	'A greenhouse conservatory in Kew Gardens, London filled with tropical palms',
	'A converted warehouse art gallery in Berlin with exposed concrete and skylights',
	'A colorful tiled interior of the Shah Mosque in Isfahan, Iran',
	'An Art Deco hotel lobby in Miami with geometric patterns and pastel walls',
	'A vaulted wine cellar in Bordeaux, France with oak barrels and stone arches',
	'A modern infinity-edge spa overlooking mountains in Bali, Indonesia',
	'A traditional Moroccan riad interior with mosaic courtyard and central fountain',
	'A grand opera house interior in Budapest, Hungary with red velvet and gold leaf',
	'A glass-walled museum corridor in the Guggenheim Bilbao with titanium curves outside',
	'A sunken living room in a mid-century modern house in Palm Springs, California',
	'A soaring nave interior in Cologne Cathedral, Germany with stained glass',
	'A tiny hole-in-the-wall ramen bar in Shinjuku, Tokyo with steam and counter seating',
	'A mirrored infinity room art installation with floating lights',
	'A cloistered courtyard in a medieval abbey in Mont Saint-Michel, France',
	'A repurposed train station food hall with iron framework and hanging gardens',
	'A white-washed cave dwelling interior in Santorini, Greece with sea-view window',
	'A candle-filled stone crypt beneath a European cathedral with vaulted arches',

	// ── Markets, Bazaars & Street Life (20) ──
	'A spice-filled souk stall in Marrakech, Morocco with pyramids of turmeric and paprika',
	'A floating market boat in Damnoen Saduak, Thailand laden with tropical fruit',
	'A vintage flea market in Portobello Road, London with antique stalls and crowds',
	'A flower market in Amsterdam, Netherlands with tulip buckets lining the canal bridge',
	'A fish market at dawn in Tsukiji, Tokyo with glistening catches on ice',
	'A fabric market stall in Jaipur, India with bolts of colorful silk and cotton',
	'A night food market in Taipei, Taiwan with steam and hanging lanterns',
	'A Christmas market in Nuremberg, Germany with wooden stalls and mulled wine steam',
	'A ceramics market in Fez, Morocco with hand-painted blue and white plates',
	'A Sunday morning farmers market in Provence, France with lavender and cheese wheels',
	'A hawker center at lunchtime in Singapore with wok flames and aromatic steam',
	'A record shop market stall in Camden, London with vinyl crates and band posters',
	'A vibrant textile bazaar in Grand Bazaar, Istanbul with hanging lamps and rugs',
	'A produce market in Oaxaca, Mexico with chili ristras and stacked tortilla baskets',
	'A second-hand book market along the Seine, Paris with green box stalls',
	'A dawn flower auction in Aalsmeer, Netherlands with millions of blooms in carts',
	'A street food alley in Penang, Malaysia with char kuey teow smoke',
	'A jade and jewelry market in Yangon, Myanmar with glass display cases',
	'A covered fish market in Bergen, Norway with fjord views through open walls',
	'A morning vegetable market in Stone Town, Zanzibar with woven baskets',

	// ── Gardens & Parks (15) ──
	'A Japanese zen garden in Ryoan-ji, Kyoto with raked white gravel and moss-covered rocks',
	'A wisteria-draped pergola in Ashikaga Flower Park, Japan in purple bloom',
	'A sculpted hedge maze in the gardens of Hampton Court Palace, England',
	'A cactus garden at Jardín de Cactus, Lanzarote with volcanic stone terraces',
	'A wildflower meadow in Kirstenbosch, Cape Town with fynbos and protea',
	'A rose garden in full bloom at Butchart Gardens, Victoria, Canada',
	'A water lily pond in Giverny, France inspired by Monet with a Japanese bridge',
	'A tropical botanical garden in Singapore with orchid-covered arches',
	'A lavender field path in Valensole, Provence, France at sunset',
	'A cherry blossom canopy in Ueno Park, Tokyo during hanami season',
	'A vertical garden wall in Madrid with thousands of plant species',
	'A sunken garden in Kensington Palace, London with formal beds and benches',
	'A terraced hillside garden in Isola Bella, Lake Maggiore, Italy',
	'A rain-soaked rhododendron garden in the English Lake District',
	'A tulip field at peak bloom in Lisse, Netherlands with windmill in background',

	// ── Rooftops & Terraces (15) ──
	'A rooftop terrace bar in Athens, Greece with the Acropolis glowing at night',
	'A vine-covered balcony overlooking Positano, Amalfi Coast, Italy',
	'A penthouse terrace in Manhattan, New York with the skyline at blue hour',
	'A whitewashed rooftop in Oia, Santorini with a blue dome church below',
	'A hotel terrace overlooking the medina of Fez, Morocco at sunset',
	'A sky garden in Marina Bay Sands, Singapore with the city spread below',
	'A rooftop infinity pool in Ubud, Bali overlooking rice terraces and jungle',
	'A weathered apartment terrace in Havana, Cuba with crumbling pastel buildings around',
	'A penthouse garden in London with the Thames and Tower Bridge in view',
	'A hilltop terrace restaurant in Ravello, Italy with the coast far below',
	'A converted warehouse rooftop in Tel Aviv, Israel with string lights at night',
	'A bell tower viewing platform in Bruges, Belgium overlooking medieval rooftops',
	'A sunrise terrace at a desert camp in Wadi Rum, Jordan',
	'A rooftop yoga deck in Tulum, Mexico with jungle canopy surrounding',
	'A castle rampart walkway in Edinburgh, Scotland overlooking the city at dusk',

	// ── Transport & Journey (15) ──
	'A vintage train compartment on the Orient Express with velvet seats and brass fittings',
	'A platform at Kandy railway station, Sri Lanka with a blue train arriving',
	'A gondola in Venice, Italy passing under a stone bridge with reflected light',
	'A yellow taxi on a bridge in Kolkata, India during monsoon rain',
	'A ferry deck crossing the Bosphorus in Istanbul, Turkey at sunset',
	'A bicycle on a country road in Tuscany, Italy with cypress tree-lined hills',
	'A wooden longtail boat on the Andaman Sea, Thailand with limestone islands ahead',
	'A cable car cabin above the clouds in Medellín, Colombia with city below',
	'A tuk-tuk ride through a narrow street in Colombo, Sri Lanka',
	'A sleeper train window view in Rajasthan, India with desert landscape passing',
	'A sailboat deck in the Aegean Sea, Greece with white island villages in the distance',
	'A motorcycle on a coastal highway in Big Sur, California with ocean cliffs',
	'A steam locomotive at a mountain station in Darjeeling, India with tea estates',
	'A kayak on the glassy waters of Milford Sound, New Zealand with waterfalls',
	'A vintage Vespa parked on a narrow street in Rome, Italy with ivy-covered walls',

	// ── Cultural & Sacred (20) ──
	'A lantern-lit temple courtyard in Chiang Mai, Thailand during Loi Krathong',
	'A candle-filled interior of a Gothic cathedral in Chartres, France',
	'A prayer wheel corridor in a Buddhist monastery in Bhutan',
	'A Shinto torii gate path at Fushimi Inari, Kyoto, Japan in soft rain',
	'A whitewashed chapel on a hillside in Mykonos, Greece with a blue door',
	'A mosque interior during golden hour in the Blue Mosque, Istanbul',
	'A Hindu temple tank in Madurai, India with colorful gopuram towers reflected',
	'A sandstone temple at sunrise in Bagan, Myanmar with hot air balloons above',
	'A synagogue interior in Prague with ornate ceiling frescoes and menorahs',
	'A candlelit memorial ceremony at Angkor Wat, Cambodia at dawn',
	'A hilltop stupa in Anuradhapura, Sri Lanka surrounded by ancient bodhi trees',
	'A traditional Balinese water temple at Tirta Empul with sacred springs',
	'An ancient amphitheater in Ephesus, Turkey with marble columns and golden light',
	'A stone circle at Callanish, Isle of Lewis, Scotland at midsummer dusk',
	'A wooden stave church in Borgund, Norway surrounded by autumn birch trees',
	'A cave monastery in Vardzia, Georgia carved into a sheer cliff face',
	'A colonial church facade in Antigua, Guatemala with jacaranda trees in bloom',
	'A silk-draped interior of a Sikh gurdwara in Amritsar, India with the Golden Temple',
	'A sunset behind the ruins of a Greek temple at Cape Sounion, Athens',
	'A candlelit procession path at the Western Wall, Jerusalem at night',

	// ── Cafés, Restaurants & Food (15) ──
	'A sidewalk café table on a Parisian boulevard with espresso and a croissant',
	'A rooftop sushi counter in Tokyo, Japan overlooking the Shibuya skyline',
	'A seaside taverna in Mykonos, Greece with blue chairs and whitewashed walls',
	'A tiny espresso bar in Naples, Italy with a marble counter and morning pastries',
	'A vineyard lunch setup in Tuscany, Italy with wine bottles and olive oil',
	'A street food stall in Mexico City with al pastor trompo and lime wedges',
	'A candlelit wine bar in a stone basement in Budapest, Hungary',
	'A beachside shack bar in Tulum, Mexico with macramé hammocks and cocktails',
	'A traditional English cream tea setup in a garden conservatory in the Cotswolds',
	'A ramen counter in Sapporo, Japan with steam rising from a miso broth bowl',
	'A terrace breakfast overlooking the Nile at a felucca stop in Luxor, Egypt',
	'A hole-in-the-wall bakery in Lisbon, Portugal with fresh pastéis de nata',
	'A farm-to-table setup on a wooden deck in Napa Valley, California',
	'A floating restaurant on a river in Chiang Rai, Thailand at sunset',
	'A Moroccan courtyard dinner setting with brass lanterns and tagine dishes',

	// ── Rural & Countryside (15) ──
	'A stone farmhouse in the Cotswolds, England with a wildflower garden gate',
	'A sunflower field at peak bloom in Valensole, Provence, France',
	'A rice paddy terrace in Tegallalang, Bali, Indonesia with coconut palms',
	'A sheep-dotted hillside in the Lake District, England with dry stone walls',
	'A wooden fence-lined ranch in Montana, USA with snow-capped Rockies behind',
	'A thatched-roof cottage in the Irish countryside with green rolling hills',
	'A vineyard row in Stellenbosch, South Africa with Cape Dutch architecture',
	'A hay bale field at golden hour in the Palouse, Washington state',
	'A windmill on a polder in Kinderdijk, Netherlands with flat green pastures',
	'A whitewashed trulli house in Alberobello, Puglia, Italy with conical stone roof',
	'A canola flower field in Luoping, Yunnan, China with karst hills',
	'A traditional wooden barn in the Appalachian Mountains during fall foliage',
	'A lavender-bordered stone path leading to a provençal mas in southern France',
	'A Highland croft with a turf roof in Skye, Scotland with sea views',
	'A tobacco drying barn in Viñales Valley, Cuba with mogote hills behind',

	// ── Arctic, Cold & Snow (10) ──
	'A Northern Lights display over a glass igloo in Lapland, Finland',
	'A frozen harbor with colorful houses in Ilulissat, Greenland with icebergs',
	'A snowy onion-domed church in Suzdal, Russia at twilight',
	'A dog sled trail through a snow-laden forest in Tromsø, Norway',
	'A hot spring with snow on the banks in Jigokudani, Japan with bathing macaques nearby',
	'An ice cave interior in Vatnajökull Glacier, Iceland with blue-white crystal walls',
	'A snow-covered wooden cabin in the Dolomites, Italy with chimney smoke',
	'A frozen lake surface in Abisko, Sweden with the aurora overhead',
	'A winter market in Reykjavik, Iceland with warm string lights and woolen stalls',
	'A snow-blanketed shrine path in Nikkō, Japan with red torii gates peeking through',

	// ── Night & Evening (15) ──
	'A starlit desert camp in the Sahara, Morocco with Milky Way overhead',
	'A lamplit canal path in Bruges, Belgium with reflections in still water',
	'A neon-lit alley in Shinjuku Golden Gai, Tokyo with tiny bar doorways',
	'A fire-lit beach gathering in Goa, India with lanterns and acoustic guitar',
	'A string-light-draped courtyard restaurant in Cartagena, Colombia',
	'A moonlit rice terrace in Ubud, Bali with firefly sparks in the air',
	'An illuminated Eiffel Tower viewed from Trocadéro at blue hour',
	'A gas-lamp-lit street in the French Quarter, New Orleans with jazz drifting out',
	'A firework display over Sydney Harbour Bridge viewed from a boat',
	'A torch-lit dinner on a sandbank in the Maldives with ocean surrounding',
	'A night market in Chiang Mai, Thailand with paper lanterns and incense smoke',
	'A cinema paradiso outdoor screening in a Sicilian piazza under the stars',
	'A glowing paper lantern release ceremony in Pingxi, Taiwan',
	'A bioluminescent kayak trail in a Puerto Rican bay under moonlight',
	'A twilight view from a hilltop in Lisbon, Portugal with the Tagus River glimmering',
];

/**
 * Shuffled queue of location indices. Guarantees every location is used
 * before any repeats. Reshuffles automatically when exhausted.
 */
let shuffledQueue: number[] = [];

function refillQueue(): void {
	shuffledQueue = Array.from({ length: LOCATIONS.length }, (_, i) => i);
	// Fisher-Yates shuffle
	for (let i = shuffledQueue.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[shuffledQueue[i], shuffledQueue[j]] = [shuffledQueue[j], shuffledQueue[i]];
	}
}

/**
 * Get the next unique location. Uses a shuffled queue so all 300 locations
 * are cycled through before any repeats.
 */
export function getNextLocation(): string {
	if (shuffledQueue.length === 0) {
		refillQueue();
	}
	return LOCATIONS[shuffledQueue.pop()!];
}

export const LOCATION_COUNT = LOCATIONS.length;
